### ISSUE TITLE
Refactoring Caja

### ISSUE THREAD

**Issue by belluccifranco** [globo-technology/sic-api#17]
- En backend, funciones de agregacion para saldo de caja por forma de pago
- Recuperar los movimientos (renglones) on demand
- Eliminar los endpoints, los saldos deberian venir con las cajas: 
@GetMapping("/cajas/{idCaja}/total")
@GetMapping("/cajas/empresas/{idEmpresa}/saldo-final")
@GetMapping("/cajas/empresas/{idEmpresa}/saldo-real")
- Nueva class en backend "MovimientoCaja" para luego recuperarlos desde la vista con un endpoint en CajaController
- Eliminar los endpoints de:
@GetMapping("/gastos/busqueda")
@GetMapping("/recibos/busqueda")
- Eliminar del service de recibos, los metodos que paginan. Lo mismo para gasto.

**Comment by k31kur0n0** [comment]
- [ ] Eliminar la hora de corte en el backEnd.
- [ ] Agregar el mensajen de "NO SE ENCONTRÓ UNA CAJA ABIERTA" al iniciar OPS. 
- [ ] Nuevo script de backfill para eliminar la hora de corte y renombrar el saldo final.

**Comment by k31kur0n0** [comment]
Quitar la vista de abrir caja, y reemplazar por una simple siguiendo el ejemplo de "Nuevo Gasto"
