### ISSUE TITLE
Refactoring integration tests

### ISSUE THREAD

**Issue by belluccifranco** [globo-technology/sic-api#187]

**Comment by k31kur0n0** [comment]
Filtro por Rubro y proveedor
rango de fechas

Ademas de meses
por semana y
por cuartos 

diferencia en porcentaje de lo pedido respecto a las ventas

filtrar resultados para mostrar cierta cantidad, dinámico

**Comment by k31kur0n0** [comment]
set @cantidadDePedidos = (select count(*) from pedido where pedido.id_Empresa = 1);

set @cantidadDeVentas
= (select count(*) from factura inner join facturaventa on factura.id_Factura = facturaventa.id_Factura);
 
select * from (
select * from (select producto.codigo as codigoProductoPedido, producto.descripcion as descripcionProductoPedido, rubro.nombre as nombrePedidoRubro, proveedor.razonSocial as razonSocialPedido,
 sum(renglonpedido.cantidad) as cantidadPedida, sum(renglonpedido.importe) as importePedido,
count(*) as cantidadDeVecesPedido, (count(*) / @cantidadDePedidos) as probabilidadDeSerPedido
 from producto 
inner join rubro on producto.id_Rubro = rubro.id_Rubro
inner join proveedor on producto.id_Proveedor = proveedor.id_Proveedor
inner join renglonpedido on producto.idProducto = renglonpedido.idProductoItem
inner join pedido on renglonpedido.id_Pedido = pedido.id_Pedido
where producto.eliminado = false and pedido.eliminado = false
and producto.id_Empresa = 1 and date(pedido.fecha) > "2017-12-31"
group by producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial
order by cantidadPedida desc) as tablaPedidos
inner join
(select producto.codigo as codigoProductoVenta, producto.descripcion as descripcionProductoVenta, rubro.nombre as nombreVentaRubro, proveedor.razonSocial as razonSocialProveedorVenta,
 sum(renglonfactura.cantidad) as cantidadVendida, sum(renglonfactura.importe) as importeVenta,
count(*) as cantidadDeVecesVendido, (count(*) / @cantidadDeVentas) as probabilidadDeSerVendido
 from producto 
inner join rubro on producto.id_Rubro = rubro.id_Rubro
inner join proveedor on producto.id_Proveedor = proveedor.id_Proveedor
inner join renglonfactura on producto.idProducto = renglonfactura.idProductoItem
inner join factura on renglonfactura.id_Factura = factura.id_Factura
where producto.eliminado = false and factura.eliminada = false
and producto.id_Empresa = 1 and date(factura.fecha) > "2017-12-31"
group by producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial
order by cantidadVendida desc) as tablaVentas
on tablaPedidos.descripcionProductoPedido = tablaVentas.descripcionProductoVenta

union all

select * from (select producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial, sum(renglonpedido.cantidad) as cantidadPedida, sum(renglonpedido.importe) as importe,
count(*) as cantidadDeVecesPedido, (count(*) / @cantidadDePedidos) as probabilidadDeSerPedido
 from producto 
inner join rubro on producto.id_Rubro = rubro.id_Rubro
inner join proveedor on producto.id_Proveedor = proveedor.id_Proveedor
inner join renglonpedido on producto.idProducto = renglonpedido.idProductoItem
inner join pedido on renglonpedido.id_Pedido = pedido.id_Pedido
where producto.eliminado = false and pedido.eliminado = false
and producto.id_Empresa = 1 and date(pedido.fecha) > "2017-12-31"
group by producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial
order by cantidadPedida desc) as tablaPedidos
left join
(select producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial, sum(renglonfactura.cantidad) as cantidadVendida, sum(renglonfactura.importe) as importe,
count(*) as cantidadDeVecesVendido, (count(*) / @cantidadDeVentas) as probabilidadDeSerVendido
 from producto 
inner join rubro on producto.id_Rubro = rubro.id_Rubro
inner join proveedor on producto.id_Proveedor = proveedor.id_Proveedor
inner join renglonfactura on producto.idProducto = renglonfactura.idProductoItem
inner join factura on renglonfactura.id_Factura = factura.id_Factura
where producto.eliminado = false and factura.eliminada = false
and producto.id_Empresa = 1 and date(factura.fecha) > "2017-12-31"
group by producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial
order by cantidadVendida desc) as tablaVentas
on tablaPedidos.descripcion = tablaVentas.descripcion
where tablaVentas.descripcion is null

union all 

select * from (select producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial, sum(renglonpedido.cantidad) as cantidadPedida, sum(renglonpedido.importe) as importe,
count(*) as cantidadDeVecesPedido, (count(*) / @cantidadDePedidos) as probabilidadDeSerPedido
 from producto 
inner join rubro on producto.id_Rubro = rubro.id_Rubro
inner join proveedor on producto.id_Proveedor = proveedor.id_Proveedor
inner join renglonpedido on producto.idProducto = renglonpedido.idProductoItem
inner join pedido on renglonpedido.id_Pedido = pedido.id_Pedido
where producto.eliminado = false and pedido.eliminado = false
and producto.id_Empresa = 1 and date(pedido.fecha) > "2017-12-31"
group by producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial
order by cantidadPedida desc) as tablaPedidos
right join
(select producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial, sum(renglonfactura.cantidad) as cantidadVendida, sum(renglonfactura.importe) as importe,
count(*) as cantidadDeVecesVendido, (count(*) / @cantidadDeVentas) as probabilidadDeSerVendido
 from producto 
inner join rubro on producto.id_Rubro = rubro.id_Rubro
inner join proveedor on producto.id_Proveedor = proveedor.id_Proveedor
inner join renglonfactura on producto.idProducto = renglonfactura.idProductoItem
inner join factura on renglonfactura.id_Factura = factura.id_Factura
where producto.eliminado = false and factura.eliminada = false
and producto.id_Empresa = 1 and date(factura.fecha) > "2017-12-31"
group by producto.codigo, producto.descripcion, rubro.nombre, proveedor.razonSocial
order by cantidadVendida desc) as tablaVentas
on tablaPedidos.descripcion = tablaVentas.descripcion
where tablaPedidos.descripcion is null) as resultado
;

**Comment by k31kur0n0** [comment]
https://support.klipfolio.com/hc/en-us/articles/216182577-DATASOURCE-function

https://support.klipfolio.com/hc/en-us/articles/215548788-Managing-your-data-sources

**Comment by k31kur0n0** [comment]
select date(fecha) as fechaRecibo, sum(monto) as montoRecibos from recibo
where recibo.id_Empresa = 1 and recibo.eliminado = false
and date(recibo.fecha) > "2017-12-31"
group by date(fecha);
-- 
select date(fecha) as fechaFectura, sum(total) as montoFactura from factura
inner join facturaventa on factura.id_Factura = facturaventa.id_Factura
where factura.id_Empresa = 1 and factura.eliminada = false
and date(factura.fecha) > "2017-12-31"
group by date(fecha);

**Comment by k31kur0n0** [comment]
select year(factura.fecha), monthname(factura.fecha), date(factura.fecha), sum(factura.total) from factura
inner join facturaventa on factura.id_Factura = facturaventa.id_Factura
where factura.id_Empresa = 1 and factura.eliminada = false
and "2018-01-01" <= date(factura.fecha)  
group by year(factura.fecha), monthname(factura.fecha), date(factura.fecha);
